### ISSUE TITLE
Vagrant : Erreur 500 secret option required for sessions

### ISSUE THREAD

**Issue by al3xLvs** [mondediefr/mondedie-chat#15]
Depuis ce commit df5d6cf74f3e7a9ca191e vagrant ne fonctionne plus

```
Error: secret option required for sessions
    at session (/home/vagrant/mondedie-chat/node_modules/express-session/index.js:167:12)
    at Layer.handle [as handle_request] (/home/vagrant/mondedie-chat/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:312:13)
    at /home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:330:12)
    at next (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/home/vagrant/mondedie-chat/node_modules/cookie-parser/index.js:54:14)
    at Layer.handle [as handle_request] (/home/vagrant/mondedie-chat/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:312:13)
    at /home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:330:12)
    at next (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:271:10)
    at /home/vagrant/mondedie-chat/node_modules/express-validator/lib/express_validator.js:228:5
    at Layer.handle [as handle_request] (/home/vagrant/mondedie-chat/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:312:13)
    at /home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:330:12)
    at next (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/vagrant/mondedie-chat/node_modules/body-parser/lib/types/urlencoded.js:88:40)
    at Layer.handle [as handle_request] (/home/vagrant/mondedie-chat/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:312:13)
    at /home/vagrant/mondedie-chat/node_modules/express/lib/router/index.js:280:7
```

**Comment by al3xLvs** [comment]
quand je commente ton if ça refonctionne @hardware 

``` js
//if(process.env.ENV === 'development')
require('dotenv').load();
```

**Comment by hardware** [comment]
Bizarre, je vais faire un test ce soir, mais je vois pas pourquoi les variables d'environnement ne s'appliquent pas correctement.

**Comment by hardware** [comment]
En fait j'ai compris, j'ai pas pensé au cas de vagrant en fait.

Il suffit juste de modifier la condition par :

`if(process.env.ENV !== 'production')`

Le fichier **.env** s'applique uniquement pour un environnement de développement, donc : 
- Local / Vagrant = **development**
- Heroku / Docker = **production**

Tout simplement.

En local, le .env s'applique via foreman ou le cookbook Chef, en prod soit c'est heroku qui applique les variables, soit docker via _EXPORT_.

Faudra aussi modifier la section docker du readme pour refléter ce changement.

**Comment by al3xLvs** [comment]
:+1: ça fonctionne
