### ISSUE TITLE
Help with Install

### ISSUE THREAD

**Issue by 0E800** [mondediefr/mondedie-chat#34]
I followed the build instructions.

location:
````/var/www/flarum/chat````

I created a ````.env```` file in /var/www/flarum/chat
I pasted the ENV as instructed on README
I create my own cookie and session unique password

When I try to login I get:
````
Erreur 500
secret option required for sessions

Error: secret option required for sessions
    at session (/var/www/keysndaggers/chat/node_modules/express-session/index.js:199:12)
    at Layer.handle [as handle_request] (/var/www/keysndaggers/chat/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:312:13)
    at /var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/var/www/keysndaggers/chat/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/var/www/keysndaggers/chat/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:312:13)
    at /var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:271:10)
    at /var/www/keysndaggers/chat/node_modules/express-validator/lib/express_validator.js:351:5
    at Layer.handle [as handle_request] (/var/www/keysndaggers/chat/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:312:13)
    at /var/www/keysndaggers/chat/node_modules/express/lib/router/index.js:280:7
````
This is my Nginx config:
````
server {
    listen 443;

    server_name chat.keys-daggers.org;

include snippets/snakeoil.conf;
    include snippets/ssl-params.conf;

    ssl on;
    add_header Strict-Transport-Security max-age=500;

    location / {
        proxy_pass http://127.0.0.1:5000; #private ip
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

location ~* \.(eot|ttf|woff|woff2)$ {
    add_header Access-Control-Allow-Origin *;
}


    gzip on;
    gzip_http_version 1.1;
    gzip_vary on;
    gzip_comp_level 6;
    gzip_proxied any;
    gzip_types application/atom+xml
               application/javascript
               application/json
               application/vnd.ms-fontobject
               application/x-font-ttf
               application/x-web-app-manifest+json
               application/xhtml+xml
               application/xml
               font/opentype
               image/svg+xml
               image/x-icon
               text/css
               text/plain
               text/xml;
    gzip_buffers 16 8k;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";
}
````

This is my Nginx error:
````
 [error] 3927#3927: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.22.2, server: chat.keys-daggers.org, request: "GET /var/www/keysndaggers/chat/node_modules/express-session/index.js HTTP/2.0", upstream: "http://127.0.0.1:5000/var/www/keysndaggers/chat/node_modules/express-session/index.js", host: "chat.keys-daggers.org"
````

May you please help?

**Comment by al3xLvs** [comment]
Sorry, we have remove dotenv https://github.com/mondediefr/mondedie-chat/commit/5fdcf6e52ae4b2bbbffa035e364cd78a8b552337

For installation I recommend you to install node-chat with docker.
