### ISSUE TITLE
ErroError: ENOENT: no such 

### ISSUE THREAD

**Issue by hexicans** [mondediefr/mondedie-chat#37]
Hello,

Après l'installation, j'ai cette erreur sur la page web : une idée ? 

`Error: ENOENT: no such file or directory, open '/home/sites/chat.oreox.fr/mondedie-chat/views/includes/build/css.pug'
   at /home/sites/chat.oreox.fr/mondedie-chat/views/layout.pug line 13
   at Object.fs.openSync (fs.js:667:18)
   at Object.fs.readFileSync (fs.js:572:33)
   at Function.read (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-load/index.js:69:13)
   at Object.read (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug/lib/index.js:141:25)
   at /home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-load/index.js:24:25
   at walkAST (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:21:18)
   at /home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:98:20
   at Array.reduce (<anonymous>)
   at walkAndMergeNodes (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:97:18)
   at walkAST (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:35:19)
   at walkAST (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:46:21)
   at /home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:98:20
   at Array.reduce (<anonymous>)
   at walkAndMergeNodes (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:97:18)
   at walkAST (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:35:19)
   at walkAST (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:46:21)
   at /home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:98:20
   at Array.reduce (<anonymous>)
   at walkAndMergeNodes (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:97:18)
   at walkAST (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-walk/index.js:35:19)
   at load (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-load/index.js:13:10)
   at Function.loadString [as string] (/home/sites/chat.oreox.fr/mondedie-chat/node_modules/pug-load/index.js:46:10)`

http://s.en-prod.org/18062018-00:09:57.png

**Comment by Hydrog3n** [comment]
Salut @hexicans, 

On dirait que tu n'as pas fait le gulp pour builder les assets. 

Tu pourrais essayer de faire : 

`yarn global add bower gulp`
`yarn install`
`gulp`

**Comment by hexicans** [comment]
Hello,

 

Pas tout semblerait-t-il en effet… Tu sais ce que je dois rentrer comme mot de passe git ? Il m’en demande un : http://s.en-prod.org/18062018-12:27:25.png


http://p.oreox.fr/A86P5N009KM

**Comment by Hydrog3n** [comment]
Ahh pas cool le repo à disparu de github... Il faut que je regarde comment faire pour que ça tourne encore. Par contre vu que le chat n'est pas vraiment maintenue selon la difficulté je le ferais pas.

**Comment by Hydrog3n** [comment]
Voilà j'ai fait une correction dit nous si tu as encore des soucis.

**Comment by hexicans** [comment]
Le build se termine bien : 

`root@redondance:/home/sites/chat.oreox.fr/mondedie-chat# gulp
[14:54:36] Using gulpfile /home/sites/chat.oreox.fr/mondedie-chat/gulpfile.js
[14:54:36] Starting 'default'...
[14:54:36] Starting 'bower'...
[14:54:36] Using cwd: /home/sites/chat.oreox.fr/mondedie-chat
[14:54:36] Using bower dir: client/bower
[14:54:36] Finished 'default' after 233 ms
[14:54:37] bower cached https://github.com/ai/visibility.js.git#1.2.8
[14:54:37] bower validate 1.2.8 against https://github.com/ai/visibility.js.git#1.2.x
[14:54:37] bower cached https://github.com/FortAwesome/Font-Awesome.git#4.7.0
[14:54:37] bower validate 4.7.0 against https://github.com/FortAwesome/Font-Awesome.git#4.7.x
[14:54:37] bower cached https://github.com/toopay/bootstrap-markdown.git#2.10.0
[14:54:37] bower validate 2.10.0 against https://github.com/toopay/bootstrap-markdown.git#2.10.x
[14:54:37] bower cached https://github.com/yuku-t/jquery-textcomplete.git#1.8.4
[14:54:37] bower validate 1.8.4 against https://github.com/yuku-t/jquery-textcomplete.git#1.8.x
[14:54:37] bower cached https://github.com/Mango/slideout.git#1.0.1
[14:54:37] bower validate 1.0.1 against https://github.com/Mango/slideout.git#1.0.x
[14:54:37] bower cached https://github.com/alexgibson/notify.js.git#2.0.3
[14:54:37] bower validate 2.0.3 against https://github.com/alexgibson/notify.js.git#2.0.x
[14:54:37] bower cached https://github.com/moment/moment.git#2.17.1
[14:54:37] bower validate 2.17.1 against https://github.com/moment/moment.git#2.17.x
[14:54:37] bower cached https://github.com/twbs/bootstrap.git#4.0.0-alpha.5
[14:54:37] bower validate 4.0.0-alpha.5 against https://github.com/twbs/bootstrap.git#v4.0.0-alpha.5
[14:54:37] bower cached https://github.com/twbs/bootstrap.git#3.3.7
[14:54:37] bower validate 3.3.7 against https://github.com/twbs/bootstrap.git#~3
[14:54:38] bower cached https://github.com/pazguille/decouple.git#0.0.2
[14:54:38] bower validate 0.0.2 against https://github.com/pazguille/decouple.git#0.0.2
[14:54:38] bower cached https://github.com/Mango/emitter.git#0.0.7
[14:54:38] bower validate 0.0.7 against https://github.com/Mango/emitter.git#0.0.7
[14:54:38] bower cached https://github.com/jquery/jquery-dist.git#3.3.1
[14:54:38] bower validate 3.3.1 against https://github.com/jquery/jquery-dist.git#>=1.7.0
[14:54:39] bower cached https://github.com/HubSpot/tether.git#1.4.4
[14:54:39] bower validate 1.4.4 against https://github.com/HubSpot/tether.git#^1.3.7
[14:54:40] bower solved Unable to find suitable version for bootstrap
[14:54:40] bower install bootstrap-markdown#2.10.0
[14:54:40] bower install visibilityjs#1.2.8
[14:54:40] bower install font-awesome#4.7.0
[14:54:40] bower install notify.js#2.0.3
[14:54:40] bower install slideout.js#1.0.1
[14:54:40] bower install jquery-textcomplete#1.8.4
[14:54:40] bower install moment#2.17.1
[14:54:40] bower install jquery#3.3.1
[14:54:40] bower install decouple#0.0.2
[14:54:40] bower install bootstrap#4.0.0-alpha.5
[14:54:40] bower install emitter-es6#0.0.7
[14:54:40] bower install tether#1.4.4
[14:54:46] Finished 'bower' after 9.54 s
[14:54:46] Starting 'clean-css'...
[14:54:46] Starting 'clean-js'...
[14:54:46] Starting 'lint'...
[14:54:46] Starting 'clean-fonts'...
[14:54:46] Starting 'emojione-strategy'...
[14:54:46] Finished 'clean-css' after 186 ms
[14:54:46] Starting 'sass'...
[14:54:46] Finished 'clean-js' after 210 ms
[14:54:46] Starting 'js'...
[14:54:46] Finished 'clean-fonts' after 44 ms
[14:54:46] Starting 'fonts'...
[14:54:46] Finished 'emojione-strategy' after 414 ms
[14:54:47] app-9cf0599da8.min.css 153.56 kB
[14:54:48] Finished 'sass' after 1.65 s
[14:54:48] Starting 'inject-css'...
[14:54:48] Finished 'fonts' after 1.62 s
[14:54:48] gulp-inject 1 files into css.pug.
[14:54:48] Finished 'inject-css' after 95 ms
[14:54:48] Finished 'lint' after 2.39 s
[14:54:48] app-1386111548.min.js.map 314.85 kB
[14:54:48] app-1386111548.min.js 315.33 kB
[14:54:48] Finished 'js' after 2.35 s
[14:54:48] Starting 'inject-js'...
[14:54:48] gulp-inject 1 files into javascript.pug.
[14:54:48] Finished 'inject-js' after 35 ms
`

Je teste.

**Comment by hexicans** [comment]
Mais après ça bloque sur ce fichier (je pense) :  **.env**

```
ENV=production
COOKIES_SECRET=fe8z64f65ze4g
SESSION_SECRET=greg5646re
FLARUM_API_ENDPOINT=http://[mon domaine]/api/
```

voilà ce que j'ai mis. Je ne remplis jamais ça car je ne suis pas habitué. Ais-je fais une erreur?

J'ai cette erreur sur le site : 
Au final, je viens de reperer mon erreur (et j'avais pas de forum flatrum par exemple ahah).
[http://s.en-prod.org/18062018-14:57:26.png](http://s.en-prod.org/18062018-14:57:26.png)

**Comment by Hydrog3n** [comment]
@hexicans yes nickel :) Pense à changer tes secrets quand même ;)
